# Generated by Django 4.2.6 on 2023-11-18 18:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_zapatilla_delete_zapatillas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapatilla',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
