# Generated by Django 4.2.6 on 2023-11-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campera', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campera',
            old_name='fecha_creación',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='estilo',
            old_name='fecha_creación',
            new_name='fecha_creacion',
        ),
    ]
