# Generated by Django 4.2.6 on 2023-11-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campera', '0003_remera_delete_estilo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Remera',
        ),
    ]
