# Generated by Django 4.2.6 on 2023-11-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campera', '0004_delete_remera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(max_length=30)),
                ('talle', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
    ]
